import { CoverImage } from "./CoverImage.slint";
import { PlayButtons } from "PlayButtons.slint";
import { TimelineSlider } from "Slider.slint";
import {Track} from "./state.slint";
import { TimeText } from "TimeText.slint";
export {Track}
export component MainWindow inherits Window {
    max-width: 7000px;
    max-height: 7000px;
    preferred-width: 817px;
    preferred-height: 1106px;
    private property <length> w: self.width;
    private property <length> h: self.height;
    padding: 20px;
    title: "";
    VerticalLayout {
        
        spacing: 30px;
        alignment: center;
        VerticalLayout {
            spacing: 15px;
        HorizontalLayout {
            Rectangle {
                horizontal-stretch: 1;
        }
            Rectangle {}
            CoverImage {
                coverImage: Track.hasCoverImage;
                coverImageSrc: Track.coverImage;
                paused: Track.paused;
                size: 200px;
                // horizontal-stretch: 1;
                // vertical-stretch: 0;
                horizontal-stretch: 0;
                // padding-left: 40px;
                // padding-right: 40px;
                // padding-left: (w - self.width)/2;
            }
            Rectangle {}
            Rectangle {
                horizontal-stretch: 1;
            }
        }
        HorizontalLayout {
            alignment: space-around;
            Text {
                font-size: 18px;
                font-weight: 600;
                text: Track.trackTitle;
            }
        }}
        VerticalLayout {
            spacing: 20px;
        HorizontalLayout {
            alignment: space-around;
            PlayButtons {
                size: 50px;
                
                // padding-left: 40px;
                // padding-right: 40px;
                // vertical-stretch: 0;
                // horizontal-stretch: 1;
                // padding-left: (w - self.width)/2; 
            }
            
        }
        HorizontalLayout {
            alignment: space-around;
            
            HorizontalLayout {
                spacing: 10px;
                VerticalLayout {
                    alignment: center;
                    TimeText {
                        time: Track.trackCurrentTime;
                        font-size: 15px;
                        font-weight: 600;
                    }
                }
            VerticalLayout {
                alignment: center;
            TimelineSlider {
                min-width: 250px;
            }}
            VerticalLayout {
                alignment: center;
            TimeText {
                font-size: 15px;
                font-weight: 600;
                time: Track.trackDuration;
            }}
            }
        }}
    }
    
}